// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
const Verifier = artifacts.require('Verifier');

contract("Verifier", accounts => {
    const account_one = accounts[0];

    describe('test with correct proof', function () {
        beforeEach(async function () {
            this.contract = await Verifier.new({from: account_one});
        });
        const proof = require("../../zokrates/code/square/proof.json");
        console.log(proof);
    });

    describe('test with incorrect proof', function () {
        beforeEach(async function () {
            this.contract = await Verifier.new({from: account_one});
        });
    });
});

// Test verification with correct proof
// - use the contents from proof.json generated from zokrates steps


// Test verification with incorrect proof
